/* 拾光所｜正式上線母版 2026-08-15 v3 */
(()=>{
const $=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),norm=s=>String(s||'').replace(/\s+/g,'');
const svc=t=>{const j=norm(t?.journey);return j.includes('同行')||j.includes('三個月')?'同行':j.includes('拾光')||j.includes('四週')?'拾光':j.includes('初遇')?'初遇':''};
const getTravelerBySelect=id=>window.data?.travelers?.find(t=>t.id===$(id)?.value)||null;
function install(){
 if(!window.data||typeof window.renderLibrary!=='function'||typeof window.confirmDraft!=='function'||typeof window.saveCloud!=='function')return false;
 if(window.__SG_MASTER_V3__)return true;window.__SG_MASTER_V3__=1;
 const css=document.createElement('style');css.textContent=`
.sg-record-actions{display:flex;gap:8px;flex-wrap:wrap}.sg-delete{border:1px solid #dfc8bd;background:#fff8f3;color:#985f56;border-radius:999px;padding:9px 14px}.sg-clean{border:1px solid #d8c6ad;background:#fffaf3;border-radius:999px;padding:9px 14px;margin-left:auto}.sg-preview-nav{display:flex;align-items:center;justify-content:center;gap:12px;margin:0 0 14px}.sg-preview-nav button{border:1px solid #dcc9ad;background:#fffaf3;border-radius:999px;padding:8px 14px}.sg-preview-count{font-size:14px;color:#8b7766}
.sg-page{position:relative;overflow:hidden;box-sizing:border-box;max-width:760px;min-height:980px;margin:0 auto;padding:34px;border:1px solid #dfceb6;border-radius:28px;color:#44382f;background:linear-gradient(135deg,#fffdf8,#f5eadb);font-family:"Songti TC","Noto Serif TC",serif;box-shadow:0 16px 40px rgba(103,78,46,.08)}.sg-page:before{content:"";position:absolute;inset:0;pointer-events:none;background:radial-gradient(circle at 12% 8%,rgba(255,255,255,.75),transparent 28%),radial-gradient(circle at 88% 16%,rgba(196,176,126,.14),transparent 22%)}.sg-page>*{position:relative;z-index:1}.sg-page.sg-page-2{background:linear-gradient(160deg,#fffdf8,#f0eadb)}.sg-page.sg-page-3{background:linear-gradient(145deg,#fbf8ef,#efe8d7)}.sg-page.sg-page-4{background:linear-gradient(155deg,#fffaf4,#eee5d5)}.sg-page.sg-page-5{background:linear-gradient(145deg,#fbf7ee,#f1e7d7)}.sg-page.sg-page-6{background:linear-gradient(155deg,#fffdf7,#eee4d3)}
.sg-head{display:grid;grid-template-columns:92px 1fr;gap:20px;align-items:center;padding-bottom:20px;border-bottom:1px solid #dfceb6}.sg-logo{width:88px;height:88px;object-fit:contain;mix-blend-mode:multiply}.sg-kicker{font-size:13px;letter-spacing:.15em;color:#9a7d54}.sg-title{font-size:34px;line-height:1.25;margin:5px 0}.sg-sub{font-size:16px;color:#806e5e;line-height:1.75}.sg-hero-note{margin:24px 0 18px;padding:17px 20px;background:rgba(255,255,255,.48);border-radius:18px;border-left:3px solid #b9a06c;line-height:1.9}.sg-sections{display:grid;gap:12px}.sg-section{padding:16px 18px 17px;background:rgba(255,253,249,.62);border-bottom:1px solid #e5d7c2}.sg-label{color:#a4814e;font-size:15px;margin-bottom:8px}.sg-label:before{content:"✦ ";}.sg-text{font-size:18px;line-height:1.85;white-space:pre-wrap}.sg-highlight{margin-top:16px;padding:20px;border-radius:18px;background:linear-gradient(90deg,rgba(232,239,215,.74),rgba(247,231,199,.56))}.sg-highlight .sg-text{font-size:20px}.sg-footer{position:absolute;left:34px;right:34px;bottom:26px;padding-top:16px;border-top:1px solid #dfceb6;color:#8a7766;font-size:14px;line-height:1.7}.sg-deco{position:absolute!important;z-index:0!important;color:#b89760;opacity:.35;font-size:62px}.sg-deco.a{right:28px;top:190px}.sg-deco.b{left:26px;bottom:86px}.sg-chip-row{display:flex;gap:10px;flex-wrap:wrap;margin:8px 0 16px}.sg-chip{padding:10px 14px;background:#f5ead7;border:1px solid #e2cfb2;border-radius:10px;font-size:16px}.sg-quote{margin:18px 0;padding:20px 22px;background:#f5eadf;border-radius:4px 18px 18px 4px;font-size:20px;line-height:1.8;border-left:4px solid #b89a67}
@media(max-width:760px){.record-row{grid-template-columns:1fr!important}.sg-record-actions button{flex:1}.sg-page{min-height:890px;padding:23px 21px;border-radius:22px}.sg-head{grid-template-columns:70px 1fr;gap:14px}.sg-logo{width:68px;height:68px}.sg-title{font-size:27px}.sg-text{font-size:16px}.sg-footer{left:22px;right:22px}.sg-preview-nav{position:sticky;top:0;z-index:4;background:rgba(249,243,233,.95);padding:8px;border-radius:14px}}
@media print{@page{size:A4;margin:0}html,body{background:#f5eee4!important;-webkit-print-color-adjust:exact!important;print-color-adjust:exact!important}body>*{display:none!important}#printSheet{display:block!important;margin:0!important;padding:0!important;background:#f5eee4!important}#printSheet .sg-page{width:210mm;max-width:none;height:297mm;min-height:297mm;margin:0;border:0;border-radius:0;box-shadow:none;padding:17mm 18mm 14mm;page-break-after:always}#printSheet .sg-page:last-child{page-break-after:auto}#printSheet .sg-head{grid-template-columns:26mm 1fr}#printSheet .sg-logo{width:24mm;height:24mm}#printSheet .sg-title{font-size:9mm}#printSheet .sg-sub{font-size:4mm}#printSheet .sg-hero-note{margin:6mm 0 4mm;padding:4mm 5mm}#printSheet .sg-sections{gap:2mm}#printSheet .sg-section{padding:3.4mm 4mm}#printSheet .sg-label{font-size:3.8mm}#printSheet .sg-text{font-size:4.3mm;line-height:1.65}#printSheet .sg-highlight{margin-top:3mm;padding:4mm 5mm}#printSheet .sg-highlight .sg-text{font-size:4.8mm}#printSheet .sg-footer{left:18mm;right:18mm;bottom:11mm;font-size:3.3mm}}
`;document.head.appendChild(css);
 const recordParts=rec=>Array.isArray(rec?.parts)&&rec.parts.length?rec.parts.map(p=>({label:p.label||'',text:p.text||'—'})):String(rec?.text||'').split(/\n\s*\n/).map(b=>{let a=b.trim().split('\n');return{label:a.shift()||'',text:a.join('\n')||'—'}}).filter(x=>x.label||x.text);
 const chunk=(arr,n)=>{let out=Array.from({length:n},()=>[]);arr.forEach((x,i)=>out[i%n].push(x));return out};
 function head(t,type,page,total,title,sub){return `<header class="sg-head"><img class="sg-logo" src="32CCD19A-16B9-451E-8559-4A40F8CA3D92.png"><div><div class="sg-kicker">拾光所｜${esc(type)} ${total>1?`${page}/${total}`:''}</div><div class="sg-title">${esc(title)}</div><div class="sg-sub">${esc(sub)}</div></div></header>`}
 function sectionHTML(items){return `<div class="sg-sections">${items.map(x=>`<section class="sg-section"><div class="sg-label">${esc(x.label)}</div><div class="sg-text">${esc(x.text)}</div></section>`).join('')}</div>`}
 function initialPages(rec,t){let p=recordParts(rec),light=p.find(x=>/拾起的光/.test(x.label)),rest=p.filter(x=>x!==light);return [`<article class="sg-page sg-page-1">${head(t,'初遇紀錄',1,1,`${t?.name||'旅人'}｜《初遇紀錄》`,'一場相遇，留下第一次看見。')}<div class="sg-deco a">❧</div><div class="sg-hero-note">一段故事，<br><strong>一次新的看見。</strong><br><span style="color:#8b7766">今天留下的，不是標準答案，而是這一次真正看見的自己。</span></div>${sectionHTML(rest)}${light?`<section class="sg-highlight"><div class="sg-label">這次拾起的光</div><div class="sg-text">${esc(light.text)}</div></section>`:''}<footer class="sg-footer">𓇼 拾光所｜陪伴每一位旅人，拾起內在的光。<br>每一次相遇，都是一束光的開始。</footer></article>`]}
 function shiguangPages(rec,t){let groups=chunk(recordParts(rec),3),titles=['這一次，我慢慢看見了自己','有些聲音聽了很久，才發現不一定都是我的','拾起的光，不是答案，而是更靠近自己的方向。'],subs=['四週的開始，把一路發生的感受留下來。','分辨外在的期待、害怕與真正的自己。','把看見帶回生活，留下真正想做的選擇。'];return groups.map((g,i)=>`<article class="sg-page sg-page-${i+1}">${head(t,'拾光紀錄',i+1,3,titles[i],subs[i])}<div class="sg-deco ${i%2?'b':'a'}">${i===0?'☾':i===1?'❧':'✦'}</div><div class="sg-hero-note">${i===0?'旅程開始時的你，和現在的你，已經不完全一樣。':i===1?'慢慢分辨：哪些是外界的聲音，哪些才是你內在真正的感受。':'不需要一次走得很遠，只要比昨天更靠近自己一點。'}</div>${sectionHTML(g)}${i===1?'<div class="sg-chip-row"><span class="sg-chip">看見</span><span class="sg-chip">分辨</span><span class="sg-chip">找回</span><span class="sg-chip">選擇</span></div>':''}${i===2?'<div class="sg-quote">「願你記得，選擇自己，不代表否定任何人。」</div>':''}<footer class="sg-footer">𓇼 拾光所｜四週旅程 · ${i+1}/3</footer></article>`)}
 function companionPages(rec,t){let groups=chunk(recordParts(rec),6),titles=['出發時的我','我看見的自己','我真正重視的事','我正在練習的選擇','現在的我','一路走來'],subs=['把最初的狀態留在這一頁。','重新認識自己，也重新理解自己的需要。','把注意力帶回真正重要的位置。','讓新的選擇慢慢發生在生活裡。','看見三個月後此刻站著的自己。','把這段旅程收進心裡，也帶回未來的日常。'];return groups.map((g,i)=>`<article class="sg-page sg-page-${i+1}">${head(t,'旅程紀錄',i+1,6,titles[i],subs[i])}<div class="sg-deco ${i%2?'b':'a'}">${['⌁','❧','✦','☕','☀','∞'][i]}</div>${sectionHTML(g)}${i===5?'<div class="sg-quote">一路走來，不是為了成為另一個人，而是越來越像真正的自己。</div>':''}<footer class="sg-footer">𓇼 拾光所｜同行 · 三個月陪伴 · ${i+1}/6</footer></article>`)}
 function pages(rec,t){return rec.type==='初遇紀錄'?initialPages(rec,t):rec.type==='拾光紀錄'?shiguangPages(rec,t):companionPages(rec,t)}
 function renderPreview(rec){let t=window.data.travelers.find(x=>x.id===rec.travelerId),pg=pages(rec,t);$('previewTitle').textContent='正式電子版預覽';$('previewSub').textContent=`${rec.type}｜共 ${pg.length} 張`;$('previewBody').innerHTML=`${pg.length>1?`<div class="sg-preview-nav"><button onclick="sgPrevPage()">← 上一張</button><span class="sg-preview-count">1 / ${pg.length}</span><button onclick="sgNextPage()">下一張 →</button></div>`:''}<div id="sgPageHost">${pg[0]}</div>`;$('recordPreviewCard').style.display='block';$('recordPreviewCard').dataset.recordId=rec.id||'';$('recordPreviewCard').dataset.page='0';window.__sgPages=pg;$('recordPreviewCard').scrollIntoView({behavior:'smooth',block:'start'})}
 window.sgPrevPage=()=>{let card=$('recordPreviewCard'),p=Math.max(0,(+card.dataset.page||0)-1);card.dataset.page=p;$('sgPageHost').innerHTML=window.__sgPages[p];document.querySelector('.sg-preview-count')&&(document.querySelector('.sg-preview-count').textContent=`${p+1} / ${window.__sgPages.length}`)};
 window.sgNextPage=()=>{let card=$('recordPreviewCard'),p=Math.min(window.__sgPages.length-1,(+card.dataset.page||0)+1);card.dataset.page=p;$('sgPageHost').innerHTML=window.__sgPages[p];document.querySelector('.sg-preview-count')&&(document.querySelector('.sg-preview-count').textContent=`${p+1} / ${window.__sgPages.length}`)};
 window.showRecordPreview=renderPreview;
 window.printRecord=()=>{let id=$('recordPreviewCard')?.dataset.recordId,rec=window.data.confirmed.find(x=>x.id===id);if(!rec)return alert('請先開啟一份正式紀錄');let t=window.data.travelers.find(x=>x.id===rec.travelerId);$('printSheet').innerHTML=pages(rec,t).join('');setTimeout(()=>window.print(),120)};
 window.saveRecordImage=async()=>{let id=$('recordPreviewCard')?.dataset.recordId,rec=window.data.confirmed.find(x=>x.id===id);if(!rec)return alert('請先開啟一份正式紀錄');if(!window.html2canvas)return alert('圖片工具尚未載入，請稍後再試。');let t=window.data.travelers.find(x=>x.id===rec.travelerId),pg=pages(rec,t),files=[];for(let i=0;i<pg.length;i++){let wrap=document.createElement('div');wrap.style.cssText='position:fixed;left:-10000px;top:0;width:760px;background:#f5eee4';wrap.innerHTML=pg[i];document.body.appendChild(wrap);let canvas=await window.html2canvas(wrap.querySelector('.sg-page'),{scale:2,backgroundColor:'#f5eee4',useCORS:true});let blob=await new Promise(r=>canvas.toBlob(r,'image/png',1));files.push(new File([blob],`${rec.type}-${i+1}.png`,{type:'image/png'}));wrap.remove()}if(navigator.share&&(!navigator.canShare||navigator.canShare({files}))){await navigator.share({files,title:'拾光所正式紀錄'});return}files.forEach((f,i)=>{let a=document.createElement('a');a.download=f.name;a.href=URL.createObjectURL(f);a.click();setTimeout(()=>URL.revokeObjectURL(a.href),60000)})};
 window.deleteSavedRecord=async id=>{let r=window.data.confirmed.find(x=>x.id===id);if(!r||!confirm('確定刪除這份正式紀錄？刪除後無法復原。'))return;window.data.confirmed=window.data.confirmed.filter(x=>x.id!==id);await window.saveCloud();window.renderLibrary()};
 window.cleanupDuplicateRecords=async()=>{let seen=new Set(),keep=[],removed=0;[...window.data.confirmed].reverse().forEach(r=>{let k=r.travelerId+'|'+r.type;if(seen.has(k))removed++;else{seen.add(k);keep.push(r)}});if(!removed)return alert('目前沒有重複紀錄。');if(!confirm(`找到 ${removed} 份重複紀錄，保留最新一份並刪除其餘項目？`))return;window.data.confirmed=keep.reverse();await window.saveCloud();window.renderLibrary()};
 window.renderLibrary=()=>{let el=$('libraryRecords');if(!el)return,rs=window.data.confirmed||[];el.innerHTML=(rs.length>1?'<div style="display:flex;margin-bottom:8px"><button class="sg-clean" onclick="cleanupDuplicateRecords()">清理重複紀錄</button></div>':'')+(rs.length?rs.map(r=>{let t=window.data.travelers.find(x=>x.id===r.travelerId);return `<div class="record-row"><div><strong>${esc(t?.name||'旅人')}｜${esc(r.type)}</strong><div class="row-meta">${esc((r.date||'').slice(0,10))}</div></div><div class="sg-record-actions"><button class="mini" onclick="viewSavedRecord('${r.id}')">查看正式版</button><button class="sg-delete" onclick="deleteSavedRecord('${r.id}')">刪除</button></div></div>`}).join(''):'<div class="empty">還沒有正式紀錄。</div>')};
 const baseConfirm=window.confirmDraft;window.confirmDraft=async()=>{let id=$('createTraveler')?.value,type=$('recordType')?.value;if(!id)return alert('請先選擇旅人');let existing=window.data.confirmed.find(r=>r.travelerId===id&&r.type===type);if(!existing)return baseConfirm();let parts=[...document.querySelectorAll('.draft-section')].map(x=>({label:x.querySelector('label')?.textContent.replace(/^\d+\s*/,'').trim()||'',text:x.querySelector('textarea')?.value.trim()||''}));existing.parts=parts;existing.text=parts.map(p=>`${p.label}\n${p.text||'—'}`).join('\n\n');existing.date=new Date().toISOString();existing.updated=Date.now();await window.saveCloud();renderPreview(existing);$('draftStatus')&&($('draftStatus').textContent='✓ 已更新原本的正式紀錄，不會新增重複卡片。');window.renderLibrary()};
 function alignType(){let t=getTravelerBySelect('createTraveler'),s=svc(t),type=s==='初遇'?'初遇紀錄':s==='拾光'?'拾光紀錄':s==='同行'?'旅程紀錄':'';if(!type||!$('recordType'))return;$('recordType').value=type;document.querySelectorAll('.record-type').forEach(x=>{let on=x.dataset.type===type;x.classList.toggle('active',on);x.style.display=on?'block':'none'})}
 const bd=window.buildDraft;if(typeof bd==='function')window.buildDraft=()=>{alignType();bd()};$('createTraveler')?.addEventListener('change',()=>setTimeout(()=>window.buildDraft?.(),0));
 function journeyRules(){let t=getTravelerBySelect('journeyTraveler'),s=svc(t),view=$('journey');if(!view)return;view.querySelectorAll('.stage-track').forEach(track=>{let st=[...track.querySelectorAll('.stage')];if(s==='初遇'){track.style.display='grid';track.style.gridTemplateColumns='1fr';st.forEach((x,i)=>x.style.display=i===0?'block':'none')}else if(s==='拾光'){track.style.display='grid';track.style.gridTemplateColumns='repeat(4,1fr)';st.forEach(x=>x.style.display='block')}else if(s==='同行')track.style.display='none'})}
 const rj=window.renderJourney;if(typeof rj==='function')window.renderJourney=()=>{rj();setTimeout(journeyRules,0)};
 function sessionRules(){let t=getTravelerBySelect('sessionTraveler'),s=svc(t),sel=$('sessionStage');if(!sel)return;if(s==='初遇'){sel.innerHTML='<option>看見</option>';sel.disabled=true}else if(s==='拾光'){sel.disabled=false;sel.innerHTML='<option>看見</option><option>分辨</option><option>找回</option><option>選擇</option>'}else if(s==='同行'){sel.disabled=false;sel.innerHTML='<option>同行</option><option>生活練習</option>'}}
 const os=window.openSessionForm;if(typeof os==='function')window.openSessionForm=()=>{os();setTimeout(sessionRules,0)};$('sessionTraveler')?.addEventListener('change',sessionRules);
 window.renderLibrary();alignType();journeyRules();document.documentElement.dataset.sgMaster='20260815-v3';return true}
let n=0,t=setInterval(()=>{if(install()||++n>150)clearInterval(t)},100);
})();