/* 拾光所｜上線前最後體驗修整 */
(()=>{
  const $=id=>document.getElementById(id);
  const isIOS=/iPad|iPhone|iPod/.test(navigator.userAgent)||(navigator.platform==='MacIntel'&&navigator.maxTouchPoints>1);

  document.addEventListener('submit',e=>{
    const btn=e.target?.querySelector('button[type="submit"]');
    if(!btn||btn.dataset.busy==='1') return;
    btn.dataset.busy='1';const old=btn.textContent;btn.textContent='儲存中…';setTimeout(()=>{btn.dataset.busy='0';btn.textContent=old},1400);
  },true);

  if(typeof window.saveRecordImage==='function')window.saveRecordImage=async()=>{
    const card=$('recordPreviewCard');if(!card||card.style.display==='none')return alert('請先完成文案確認，再儲存正式圖片。');if(!window.html2canvas)return alert('圖片工具尚未載入，請稍後再試。');
    try{const canvas=await window.html2canvas(card,{scale:2,backgroundColor:'#fffaf4',useCORS:true});const name=($('previewTitle')?.textContent||'拾光所紀錄').replace(/[\\/:*?"<>|]/g,'-')+'.png';const blob=await new Promise(r=>canvas.toBlob(r,'image/png',1));if(blob&&navigator.share){const file=new File([blob],name,{type:'image/png'});if(!navigator.canShare||navigator.canShare({files:[file]})){await navigator.share({files:[file],title:'拾光所旅程紀錄'});return}}if(isIOS){const url=URL.createObjectURL(blob);const w=window.open(url,'_blank');if(!w)location.href=url;setTimeout(()=>URL.revokeObjectURL(url),60000);return}const a=document.createElement('a');a.download=name;a.href=canvas.toDataURL('image/png');a.click()}catch(err){console.error(err);alert('圖片儲存沒有成功，請再試一次。')}};

  const safeCreate=()=>{if(!window.data?.travelers?.length){alert('先建立第一位旅人，再開始製作旅程紀錄。');return false}return true};
  document.querySelectorAll('[onclick*="go(\'create\')"],[onclick*="go(\"create\")"]').forEach(el=>el.addEventListener('click',e=>{if(!safeCreate()){e.preventDefault();e.stopImmediatePropagation()}},true));
  document.addEventListener('focusin',e=>{if(!/INPUT|TEXTAREA|SELECT/.test(e.target?.tagName||''))return;setTimeout(()=>e.target.scrollIntoView({behavior:'smooth',block:'center'}),220)});

  const normalize=t=>(t||'').replace(/\s+/g,'');
  function getTravelerBySelect(id){const tid=$(id)?.value;return window.data?.travelers?.find(x=>x.id===tid)||null}
  function serviceOfTraveler(t){const j=normalize(t?.journey||'');if(j.includes('同行')||j.includes('三個月'))return'同行';if(j.includes('拾光')||j.includes('四週'))return'拾光';if(j.includes('初遇'))return'初遇';return''}
  function fixJourneyStages(){const view=$('journey');if(!view||!view.classList.contains('active'))return;const service=serviceOfTraveler(getTravelerBySelect('journeyTraveler'));view.querySelectorAll('.stage-track').forEach(track=>{if(service==='初遇'){track.style.display='grid';track.style.gridTemplateColumns='1fr';[...track.querySelectorAll('.stage')].forEach((s,i)=>s.style.display=i===0?'block':'none')}else if(service==='拾光'){track.style.display='grid';track.style.gridTemplateColumns='repeat(4,1fr)';[...track.querySelectorAll('.stage')].forEach(s=>s.style.display='block')}else if(service==='同行')track.style.display='none'})}
  function fixSessionByService(){const view=$('session');if(!view||!view.classList.contains('active'))return;const service=serviceOfTraveler(getTravelerBySelect('sessionTraveler')),sel=$('sessionStage');if(!sel)return;const keep=sel.value;if(service==='初遇'){sel.innerHTML='<option value="看見">看見</option>';sel.value='看見';sel.disabled=true;view.querySelectorAll('.stage-track').forEach(track=>{track.style.display='grid';track.style.gridTemplateColumns='1fr';[...track.querySelectorAll('.stage')].forEach((s,i)=>s.style.display=i===0?'block':'none')})}else if(service==='拾光'){sel.disabled=false;sel.innerHTML='<option>看見</option><option>分辨</option><option>找回</option><option>選擇</option>';if([...sel.options].some(o=>o.value===keep))sel.value=keep;view.querySelectorAll('.stage-track').forEach(track=>{track.style.display='grid';track.style.gridTemplateColumns='repeat(4,1fr)';[...track.querySelectorAll('.stage')].forEach(s=>s.style.display='block')})}else if(service==='同行'){sel.disabled=false;sel.innerHTML='<option>同行</option><option>生活練習</option>';if([...sel.options].some(o=>o.value===keep))sel.value=keep;view.querySelectorAll('.stage-track').forEach(track=>track.style.display='none')}}
  const originalOpenSession=window.openSessionForm;if(typeof originalOpenSession==='function')window.openSessionForm=()=>{originalOpenSession();setTimeout(fixSessionByService,30)};$('sessionTraveler')?.addEventListener('change',fixSessionByService);
  function recordTypeForTraveler(t){const s=serviceOfTraveler(t);return s==='初遇'?'初遇紀錄':s==='拾光'?'拾光紀錄':s==='同行'?'旅程紀錄':''}
  function alignRecordType(){const t=getTravelerBySelect('createTraveler');if(!t)return;const type=recordTypeForTraveler(t);if(!type)return;const hidden=$('recordType');if(hidden&&hidden.value!==type){hidden.value=type;document.querySelectorAll('.record-type').forEach(x=>x.classList.toggle('active',x.dataset.type===type))}document.querySelectorAll('.record-type').forEach(x=>{const active=x.dataset.type===type;x.style.opacity=active?'1':'.42';x.style.pointerEvents=active?'auto':'none'})}
  $('createTraveler')?.addEventListener('change',()=>setTimeout(()=>{alignRecordType();window.buildDraft?.()},20));const originalBuildDraft=window.buildDraft;if(typeof originalBuildDraft==='function')window.buildDraft=()=>{alignRecordType();originalBuildDraft()};
  const observer=new MutationObserver(()=>requestAnimationFrame(()=>{fixJourneyStages();fixSessionByService();alignRecordType()}));observer.observe(document.body,{subtree:true,childList:true,attributes:true,attributeFilter:['class']});document.addEventListener('click',()=>setTimeout(()=>{fixJourneyStages();fixSessionByService();alignRecordType()},40),true);setTimeout(()=>{fixJourneyStages();fixSessionByService();alignRecordType()},80);

  const previewStyle=document.createElement('style');previewStyle.textContent=`#recordPreviewCard{background:radial-gradient(circle at 10% 5%,rgba(255,255,255,.92),transparent 35%),linear-gradient(145deg,#fffaf4,#f2e4d1)!important;border-color:#dfcdb3!important;padding:28px!important}.sg-preview-grid{display:grid;gap:12px}.sg-preview-item{padding:15px 16px;border-bottom:1px solid #eadfce}.sg-preview-item:last-child{border-bottom:0}.sg-preview-label{font-family:"Songti TC","Noto Serif TC",serif;color:#9b7b50;font-size:15px;margin-bottom:7px}.sg-preview-label:before{content:"✦ ";color:#b79560}.sg-preview-text{font-family:"Songti TC","Noto Serif TC",serif;white-space:pre-wrap;line-height:1.9;font-size:17px;color:#493d34}.sg-preview-foot{margin-top:18px;text-align:right;font-family:"Songti TC","Noto Serif TC",serif;color:#8b7766;font-size:14px}.sg-record-actions{display:flex;gap:8px;align-items:center;flex-wrap:wrap}.sg-delete-record{border:1px solid #e5c9c1;background:#fff8f5;color:#9b5f57;border-radius:999px;padding:8px 12px;cursor:pointer}@media(max-width:760px){#recordPreviewCard{padding:18px!important}.sg-preview-item{padding:13px 8px}.sg-preview-text{font-size:16px}.record-row{grid-template-columns:1fr!important}.sg-record-actions{margin-top:8px}}`;document.head.appendChild(previewStyle);
  function escHtml(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
  function recParts(rec){if(Array.isArray(rec?.parts)&&rec.parts.length)return rec.parts.map(p=>({label:p.label||'',text:p.text||'—'}));const text=rec?.text||$('previewBody')?.textContent||'';return text.split(/\n\s*\n/).map(x=>x.trim()).filter(Boolean).map(block=>{const lines=block.split('\n');return{label:(lines.shift()||'').trim(),text:lines.join('\n').trim()||'—'}})}
  window.showRecordPreview=rec=>{const t=window.data?.travelers?.find(x=>x.id===rec.travelerId),title=`${t?.name||'旅人'}｜《${rec.type}》`,sub=rec.type==='初遇紀錄'?'一場相遇，留下第一次看見。':rec.type==='拾光紀錄'?'四週整理，把一路看見的自己留下來。':'三個月，把真正發生在生活裡的改變留下來。';$('previewTitle').textContent=title;$('previewSub').textContent=sub;const parts=recParts(rec);$('previewBody').innerHTML=`<div class="sg-preview-grid">${parts.map(p=>`<div class="sg-preview-item"><div class="sg-preview-label">${escHtml(p.label)}</div><div class="sg-preview-text">${escHtml(p.text)}</div></div>`).join('')}</div><div class="sg-preview-foot">𓇼 拾光所｜陪伴每一位旅人，拾起內在的光。</div>`;$('recordPreviewCard').style.display='block';$('recordPreviewCard').dataset.recordId=rec.id||'';$('recordPreviewCard').scrollIntoView({behavior:'smooth',block:'start'})};

  /* 同一位旅人、同一種紀錄：再次確認時更新原紀錄，不再一直新增重複卡片。 */
  const originalConfirmDraft=window.confirmDraft;
  if(typeof originalConfirmDraft==='function')window.confirmDraft=async()=>{
    const travelerId=$('createTraveler')?.value,type=$('recordType')?.value;if(!travelerId)return alert('請先選擇旅人');
    const existing=window.data?.confirmed?.find(r=>r.travelerId===travelerId&&r.type===type);
    if(!existing)return originalConfirmDraft();
    const parts=[...document.querySelectorAll('.draft-section')].map(x=>({label:x.querySelector('label')?.textContent.replace(/^\d+\s*/,'').trim()||'',text:x.querySelector('textarea')?.value.trim()||''}));existing.parts=parts;existing.text=parts.map(p=>`${p.label}\n${p.text||'—'}`).join('\n\n');existing.date=new Date().toISOString();existing.updated=Date.now();await window.saveCloud?.();window.showRecordPreview(existing);$('draftStatus').textContent='✓ 已更新原本的正式紀錄，不會重複新增。';window.renderLibrary?.();
  };

  window.deleteSavedRecord=async id=>{const rec=window.data?.confirmed?.find(r=>r.id===id);if(!rec)return;if(!confirm('確定要刪除這份正式紀錄嗎？刪除後無法復原。'))return;window.data.confirmed=window.data.confirmed.filter(r=>r.id!==id);if($('recordPreviewCard')?.dataset.recordId===id){$('recordPreviewCard').style.display='none';$('recordPreviewCard').dataset.recordId=''}await window.saveCloud?.();window.renderLibrary?.()};
  window.renderLibrary=()=>{const el=$('libraryRecords');if(!el)return;const records=window.data?.confirmed||[];el.innerHTML=records.length?records.map(r=>{const t=window.data?.travelers?.find(x=>x.id===r.travelerId);return`<div class="record-row"><div><strong>${escHtml(t?.name||'旅人')}｜${escHtml(r.type)}</strong><div class="row-meta">${escHtml((r.date||'').slice(0,10))}</div></div><div class="sg-record-actions"><button class="mini" onclick="viewSavedRecord('${r.id}')">查看正式版</button><button class="sg-delete-record" onclick="deleteSavedRecord('${r.id}')">刪除</button></div></div>`}).join(''):'<div class="empty">還沒有正式紀錄。完成文案確認後，會自動收藏在這裡。</div>'};

  const printStyle=document.createElement('style');printStyle.textContent=`@media print{@page{size:A4;margin:0}html,body{background:#f4ecdf!important;-webkit-print-color-adjust:exact!important;print-color-adjust:exact!important}body>*{display:none!important}#printSheet{display:block!important;width:210mm;min-height:297mm;margin:0;padding:0!important;background:#f8f2e8!important;color:#493c31!important;font-family:"Songti TC","Noto Serif TC",serif!important}.sg-print-page{width:210mm;min-height:297mm;padding:16mm;position:relative;background:linear-gradient(180deg,#fbf7f0,#f4eadc)!important}.sg-print-brand{display:flex;align-items:center;justify-content:space-between;padding-bottom:8mm;border-bottom:.35mm solid #d9c6aa}.sg-print-brand-left{display:flex;align-items:center;gap:5mm}.sg-print-logo{width:24mm;height:24mm;object-fit:contain;mix-blend-mode:multiply}.sg-print-name{font-size:8mm;letter-spacing:1.5mm}.sg-print-tag{font-size:3.7mm;color:#8a7868}.sg-print-record{margin-top:13mm;padding:11mm 12mm;border:.35mm solid #e2d2bd;border-radius:7mm;background:rgba(255,252,247,.82)}.sg-print-kicker{font-size:3.6mm;color:#9b825f}.sg-print-title{font-size:11mm;margin:3mm 0 2mm;color:#5a4128}.sg-print-sub{font-size:4.4mm;color:#8b7563;margin-bottom:8mm}.sg-print-item{padding:4mm 0;border-bottom:.25mm solid #eadfce}.sg-print-label{font-size:4mm;color:#9c7e55;margin-bottom:1.6mm}.sg-print-text{font-size:4.8mm;line-height:1.85;white-space:pre-wrap}.sg-print-footer{position:absolute;left:16mm;right:16mm;bottom:12mm;display:flex;justify-content:space-between;border-top:.3mm solid #decdb6;padding-top:4mm}.sg-print-quote,.sg-print-date{font-size:3.7mm;color:#7d6959}}`;document.head.appendChild(printStyle);
  function currentPreviewParts(){const items=[...document.querySelectorAll('#previewBody .sg-preview-item')];return items.length?items.map(x=>({label:x.querySelector('.sg-preview-label')?.textContent?.replace(/^✦\s*/,'')||'',text:x.querySelector('.sg-preview-text')?.textContent||'—'})):[]}
  window.printRecord=()=>{const title=$('previewTitle')?.textContent||'《旅程紀錄》',sub=$('previewSub')?.textContent||'',parts=currentPreviewParts(),sheet=$('printSheet'),today=new Intl.DateTimeFormat('zh-TW',{year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());sheet.innerHTML=`<div class="sg-print-page"><div class="sg-print-brand"><div class="sg-print-brand-left"><img class="sg-print-logo" src="32CCD19A-16B9-451E-8559-4A40F8CA3D92.png"><div><div class="sg-print-name">拾光所</div><div class="sg-print-tag">陪伴每一位旅人，拾起內在的光。</div></div></div><div class="sg-print-kicker">一頁珍藏</div></div><section class="sg-print-record"><div class="sg-print-kicker">SHIGUANG JOURNEY RECORD</div><h1 class="sg-print-title">${escHtml(title)}</h1><div class="sg-print-sub">${escHtml(sub)}</div>${parts.map(p=>`<div class="sg-print-item"><div class="sg-print-label">✦ ${escHtml(p.label)}</div><div class="sg-print-text">${escHtml(p.text)}</div></div>`).join('')}</section><footer class="sg-print-footer"><div class="sg-print-quote">每一次相遇，都留下一點重新看見自己的光。</div><div class="sg-print-date">${escHtml(today)}<br>𓇼 拾光所</div></footer></div>`;setTimeout(()=>window.print(),80)};
  document.documentElement.dataset.shiguangBuild='launch-5';
})();