/* 拾光所｜正式電子紀錄母版 2026-08-15 v2 */
(()=>{
const $=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function install(){if(!window.data||!window.renderLibrary)return false;if(window.__SG_MASTER_V2__)return true;window.__SG_MASTER_V2__=1;
const css=document.createElement('style');css.textContent=`
.sg-record-actions{display:flex;gap:8px;flex-wrap:wrap}.sg-delete{border:1px solid #dfc8bd;background:#fff8f3;color:#985f56;border-radius:999px;padding:9px 14px}.sg-clean{border:1px solid #d8c6ad;background:#fffaf3;border-radius:999px;padding:9px 14px;margin-left:auto}
.sg-keepsake{position:relative;overflow:hidden;max-width:760px;margin:auto;padding:34px 34px 28px;border:1px solid #dfceb6;border-radius:28px;color:#44382f;background:linear-gradient(135deg,rgba(255,252,245,.98),rgba(248,239,224,.96));font-family:"Songti TC","Noto Serif TC",serif;box-shadow:0 16px 40px rgba(103,78,46,.08)}
.sg-keepsake:before{content:"";position:absolute;right:-55px;top:-65px;width:230px;height:230px;border-radius:50%;background:radial-gradient(circle,rgba(206,184,135,.22),transparent 68%)}.sg-keepsake:after{content:"❧  ·  ✦  ·  ❧";position:absolute;right:30px;bottom:24px;color:#b79a68;font-size:18px;opacity:.65}
.sg-k-head{display:grid;grid-template-columns:92px 1fr;gap:20px;align-items:center;padding-bottom:22px;border-bottom:1px solid #dfceb6}.sg-k-logo{width:88px;height:88px;object-fit:contain;mix-blend-mode:multiply}.sg-k-kicker{font-size:14px;letter-spacing:.16em;color:#9a7d54}.sg-k-title{font-size:34px;line-height:1.25;margin:5px 0}.sg-k-sub{font-size:16px;color:#806e5e;line-height:1.8}.sg-k-intro{margin:25px 0 18px;padding:18px 20px;background:rgba(255,255,255,.45);border-radius:18px;border-left:3px solid #b9a06c;line-height:1.9}.sg-k-grid{display:grid;gap:14px}.sg-k-item{position:relative;padding:17px 18px 18px;background:rgba(255,253,249,.62);border-bottom:1px solid #e5d7c2}.sg-k-label{color:#a4814e;font-size:15px;margin-bottom:9px}.sg-k-label:before{content:"✦ ";}.sg-k-text{font-size:18px;line-height:1.9;white-space:pre-wrap}.sg-k-light{margin-top:18px;padding:20px;border-radius:18px;background:linear-gradient(90deg,rgba(232,239,215,.72),rgba(247,231,199,.52));}.sg-k-light .sg-k-text{font-size:20px}.sg-k-foot{margin-top:24px;padding-top:18px;border-top:1px solid #dfceb6;color:#8a7766;font-size:14px;line-height:1.8}.sg-k-note{font-size:13px;color:#a58c70;margin-top:7px}
@media(max-width:760px){.record-row{grid-template-columns:1fr!important}.sg-record-actions button{flex:1}.sg-keepsake{padding:24px 22px;border-radius:22px}.sg-k-head{grid-template-columns:72px 1fr;gap:14px}.sg-k-logo{width:70px;height:70px}.sg-k-title{font-size:27px}.sg-k-text{font-size:17px}}
@media print{@page{size:A4;margin:0}html,body{background:#f5eee4!important;-webkit-print-color-adjust:exact!important;print-color-adjust:exact!important}body>*{display:none!important}#printSheet{display:block!important;width:210mm;height:297mm;margin:0!important;padding:0!important;background:#f6eee2!important}#printSheet .sg-keepsake{box-sizing:border-box;width:210mm;max-width:none;height:297mm;border:0;border-radius:0;box-shadow:none;padding:18mm 18mm 14mm;background:linear-gradient(135deg,#fffdf8,#f4e8d7)}#printSheet .sg-k-head{grid-template-columns:27mm 1fr}#printSheet .sg-k-logo{width:25mm;height:25mm}#printSheet .sg-k-title{font-size:9mm}#printSheet .sg-k-sub{font-size:4mm}#printSheet .sg-k-intro{margin:7mm 0 4mm;padding:4mm 5mm}#printSheet .sg-k-grid{gap:2mm}#printSheet .sg-k-item{padding:3.4mm 4mm}#printSheet .sg-k-label{font-size:3.8mm;margin-bottom:1mm}#printSheet .sg-k-text{font-size:4.3mm;line-height:1.65}#printSheet .sg-k-light{margin-top:4mm;padding:4mm 5mm}#printSheet .sg-k-light .sg-k-text{font-size:4.8mm}#printSheet .sg-k-foot{margin-top:5mm;padding-top:3mm;font-size:3.4mm}}
`;document.head.appendChild(css);
const parts=rec=>Array.isArray(rec?.parts)&&rec.parts.length?rec.parts.map(p=>({label:p.label||'',text:p.text||'—'})):String(rec?.text||'').split(/\n\s*\n/).map(b=>{let a=b.trim().split('\n');return{label:a.shift()||'',text:a.join('\n')||'—'}});
function keepsake(rec,t){let p=parts(rec);let light=p.find(x=>/拾起的光/.test(x.label));let rest=p.filter(x=>x!==light);let title=rec.type==='初遇紀錄'?'初遇紀錄':rec.type==='拾光紀錄'?'拾光紀錄':'旅程紀錄';let sub=rec.type==='初遇紀錄'?'一場相遇，留下第一次看見。':rec.type==='拾光紀錄'?'四週整理，把一路看見的自己留下來。':'三個月，把真正發生在生活裡的改變留下來。';return `<article class="sg-keepsake"><header class="sg-k-head"><img class="sg-k-logo" src="32CCD19A-16B9-451E-8559-4A40F8CA3D92.png"><div><div class="sg-k-kicker">拾光所｜${esc(title)}</div><div class="sg-k-title">${esc(t?.name||'旅人')}｜《${esc(title)}》</div><div class="sg-k-sub">${esc(sub)}</div></div></header><div class="sg-k-intro">今天留下的，不是為了替自己找到一個標準答案，<br>而是把這一次真正看見的自己，好好收藏下來。</div><div class="sg-k-grid">${rest.map(x=>`<section class="sg-k-item"><div class="sg-k-label">${esc(x.label)}</div><div class="sg-k-text">${esc(x.text)}</div></section>`).join('')}</div>${light?`<section class="sg-k-light"><div class="sg-k-label">這次拾起的光</div><div class="sg-k-text">${esc(light.text)}</div></section>`:''}<footer class="sg-k-foot">𓇼 拾光所｜陪伴每一位旅人，拾起內在的光。<div class="sg-k-note">每一次相遇，都是一束光的開始。</div></footer></article>`}
window.showRecordPreview=rec=>{let t=window.data.travelers.find(x=>x.id===rec.travelerId);$('previewTitle').textContent='正式電子版預覽';$('previewSub').textContent='預覽、圖片與 PDF 使用同一份母版';$('previewBody').innerHTML=keepsake(rec,t);$('recordPreviewCard').style.display='block';$('recordPreviewCard').dataset.recordId=rec.id||'';$('recordPreviewCard').scrollIntoView({behavior:'smooth',block:'start'})};
window.printRecord=()=>{let id=$('recordPreviewCard')?.dataset.recordId,rec=window.data.confirmed.find(x=>x.id===id);if(!rec)return alert('請先開啟一份正式紀錄');let t=window.data.travelers.find(x=>x.id===rec.travelerId);$('printSheet').innerHTML=keepsake(rec,t);setTimeout(()=>window.print(),100)};
window.deleteSavedRecord=async id=>{let r=window.data.confirmed.find(x=>x.id===id);if(!r||!confirm('確定刪除這份正式紀錄？刪除後無法復原。'))return;window.data.confirmed=window.data.confirmed.filter(x=>x.id!==id);await window.saveCloud();window.renderLibrary()};
window.cleanupDuplicateRecords=async()=>{let seen=new Set(),keep=[],removed=0;[...window.data.confirmed].reverse().forEach(r=>{let k=r.travelerId+'|'+r.type;if(seen.has(k))removed++;else{seen.add(k);keep.push(r)}});if(!removed)return alert('目前沒有重複紀錄。');if(!confirm(`找到 ${removed} 份重複紀錄，保留最新一份並刪除其餘項目？`))return;window.data.confirmed=keep.reverse();await window.saveCloud();window.renderLibrary()};
window.renderLibrary=()=>{let el=$('libraryRecords');if(!el)return;let rs=window.data.confirmed||[];el.innerHTML=(rs.length>1?'<div style="display:flex;margin-bottom:8px"><button class="sg-clean" onclick="cleanupDuplicateRecords()">清理重複紀錄</button></div>':'')+(rs.length?rs.map(r=>{let t=window.data.travelers.find(x=>x.id===r.travelerId);return `<div class="record-row"><div><strong>${esc(t?.name||'旅人')}｜${esc(r.type)}</strong><div class="row-meta">${esc((r.date||'').slice(0,10))}</div></div><div class="sg-record-actions"><button class="mini" onclick="viewSavedRecord('${r.id}')">查看正式版</button><button class="sg-delete" onclick="deleteSavedRecord('${r.id}')">刪除</button></div></div>`}).join(''):'<div class="empty">還沒有正式紀錄。</div>')};
window.renderLibrary();document.documentElement.dataset.sgMaster='20260815-v2';return true}
let n=0,t=setInterval(()=>{if(install()||++n>120)clearInterval(t)},100);
})();